---
title: "Dimensionality reduction for distance object describing settlement networks"
author: "Mikhail Orlov"
date: '6 ноября 2017 г '
output:
  html_document: default
pdf_document: default
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Clearing workspace, setting working directory and loading R packages
```{r, message=FALSE}
rm(list=ls())
```


Loading data
```{r Data}

load('/home/jane/Документы/Misha/sheludkov/Settlements-Network-Population-Dynamics/data/matrix_2002.Rdata')
load('/home/jane/Документы/Misha/sheludkov/Settlements-Network-Population-Dynamics/data/matrix_2010.Rdata')

#workspace loading
load("/home/jane/Документы/Misha/sheludkov/Settlements-Network-Population-Dynamics/data/Part2_output.RData")
```


```{r clusters labels and villages names}

clusts_18_colors <- rainbow(18)[settlements_2002@data$clust_18]
clusts_6_colors <- rainbow(6)[settlements_2002@data$clust_6]

village_names <- settlements_2002@data$ShortName
#libraries
```

```{r 1 MDS}
fit_18_clusts <- cmdscale(dist_matrix_2002, eig = TRUE, k = 18)
x_18_clusts <- fit_18_clusts$points[, 1]
y_18_clusts <- fit_18_clusts$points[, 2]

fit_6_clusts <- cmdscale(dist_matrix_2002, eig = TRUE, k = 6)
x_6_clusts <- fit_6_clusts$points[, 1]
y_6_clusts <- fit_6_clusts$points[, 2]
```

```{r MDS plots}
#showing only part of villages names
inds <- seq(1, to = length(village_names), by = 1)
# #par(mfrow = c(2,1))
png('/home/jane/Документы/Misha/sheludkov/Settlements-Network-Population-Dynamics/MDS_18_clusters_plot_all_labels.png', width = 1500, height = 1500, res = 250)
plot(x_18_clusts, y_18_clusts, pch = 19, xlim = range(x_18_clusts), col = clusts_18_colors, main = 'Multidimensional Scaling Visualization\n for 18 Clusters (2002 Data)')
text(x_18_clusts[inds], y_18_clusts[inds], pos = rep(1:4, length(village_names)/4), labels = village_names[inds], cex = 0.2, col = 1)
dev.off()

#legend('topright', legend = paste('Cluster', 1:18), col = rainbow(18), lty = 1, cex= 0.5)
png('/home/jane/Документы/Misha/sheludkov/Settlements-Network-Population-Dynamics/MDS_6_clusters_plot_all_labels.png', width = 1500, height = 1500, res = 250)
plot(x_6_clusts, y_6_clusts, pch = 19, xlim = range(x_6_clusts), col = clusts_6_colors, main = 'Multidimensional Scaling Visualization\n for 6 Clusters (2002 Data)')
text(x_18_clusts[inds], y_18_clusts[inds], pos = rep(1:4, length(village_names)/4), labels = village_names[inds], cex = 0.2, col = 1)
#legend('topright', legend = paste('Cluster', 1:6), col = rainbow(6), lty = 1, cex= 0.5)
dev.off()


```

```{r 2 t-SNE}

library(Rtsne)
tsne <- Rtsne(as.dist(dist_matrix_2002), dims = 2, perplexity=30, verbose=TRUE, max_iter = 500)

## Plotting
# #par(mfrow = c(2,1))
png('/home/jane/Документы/Misha/sheludkov/Settlements-Network-Population-Dynamics/tSNE_6_clusters_plot_all_labels.png', width = 1500, height = 1500, res = 250)
plot(tsne$Y, t='p',  col=clusts_18_colors, cex = 1, main = 't-SNE Visualization\n for 18 Clusters (2002 Data)')
text(tsne$Y[inds,], pos = rep(1:4, length(village_names)/4), labels=village_names[inds], col=1, cex = 0.3)
dev.off()

png('/home/jane/Документы/Misha/sheludkov/Settlements-Network-Population-Dynamics/tSNE_18_clusters_plot_all_labels.png', width = 1500, height = 1500, res = 250)
plot(tsne$Y, t='p',  col=clusts_6_colors, cex = 1, main = 't-SNE Visualization\n for 6 Clusters (2002 Data)')
text(tsne$Y[inds,], pos = rep(1:4, length(village_names)/4), labels=village_names[inds], col=1, cex = 0.3)
dev.off()
```